---
title: "Untitled"
output: html_document
date: '2022-04-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
getwd()
```



```{r}
data_tidy <- read_csv("data/data_tidy.csv") %>% 
  as_tibble()

data_tidy 
```

```{r}
data_tidy <- data_tidy %>% 
  as_tibble()

data_tidy 
```


```{r}
ggplot(data = data_tidy,
       mapping = aes(x = smoking,
                       y = survival_days)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(mapping = aes(fill = nodal_involvement),
              shape = 21,
              color = "black") 
  #facet_wrap(vars(species),
              #    ncol = 2,
               #   scales = "free_y")
```

```{r}

data_tidy %>% 
  select(-contains("mmu"))
```


What I will be doing:
- Download txt file from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GPL8835&id=30413&db=GeoDb_blob35 to get the miRNA names
- I should probably end up with something like this https://www.ebi.ac.uk/arrayexpress/files/A-GEOD-13415/A-GEOD-13415.adf.txt



```{r}
data_tidy %>% 
  select(contains("hsa-miR"))
```




